### ISSUE TITLE
如何显示成中文？

### ISSUE THREAD

**Issue by Jetive** [newnight/SnailSvn-helper-vscode#1]
非常非常好用，不小心用到了SnailSVN这个app，在Mac上实现了和乌龟一模一样的体验，又好巧找到了这个vscode扩展，实在是太方便啦！

有一点点小问题，关于中文显示的。

在菜单上，目前显示的是 Snailsvn Update ，我该如何让让它显示成“Snailsvn更新“呢？
其他的地方我也想改成中文显示，能否加个”扩展设置“的功能，方便自己去配置文件里改这些显示的字眼。

**Comment by newnight** [comment]
菜单项貌似不能做成设置项，近期有空了我加一下默认的中文支持

**Comment by newnight** [comment]
@Jetive ,翻译功能已添加，欢迎 试用并评分哈：
1. 直接修改`SnailSvn.localizeSetting` 对应的 Value值, 可以替换成自己喜欢的 emoji 表情.
2. 改完对应的菜单项翻译后,需要右键触发任一 SnailSVN 命令 或者直接触发`Snailsvn resetLocalize`命令, 然后重启Vscode, 使修改生效.

**Comment by Jetive** [comment]
谢谢！大大的赞～
